In [3]:
# ! pip install git+https://gitlab.com/ase/ase@master
# ! pip install ase

# Convert format
See [ase.io](https://wiki.fysik.dtu.dk/ase/ase/io/io.html)

## Write atoms to file

### To trajectory 

In [ ]:
from ase.io.trajectory import Trajectory

Trajectory('ch4.traj', 'w').write(atoms)  # noqa: F821


### To Lammps_data

In [ ]:
from ase.io.lammpsdata import write_lammps_data

write_lammps_data('CH4.data', atoms, atom_style='atomic', masses=True)  # noqa: F821

## Read atoms from file

### From Lammps_data

In [ ]:
from ase.io import read
from ase.visualize import view

os.chdir(run_dir.parent / "2_DeepMDkit/test_file")  # noqa: F821
atoms = read('CH4.data', format='lammps-data')

In [14]:
view(atoms)

<Popen: returncode: None args: ['c:\\DevProgram\\miniconda3\\envs\\py12\\pyt...>

In [15]:
atoms.pbc

array([ True,  True,  True])

### From POSCAR VASP

In [25]:
atoms = read('POSCAR', format='vasp')

In [ ]:
atoms.get_chemical_symbols()

In [17]:
view(atoms)

<Popen: returncode: None args: ['c:\\DevProgram\\miniconda3\\envs\\py12\\pyt...>

In [24]:
atoms.get_positions()

array([[4.65255, 3.49679, 4.42777],
       [3.92359, 4.7445 , 4.96772],
       [5.10644, 5.63801, 4.43427],
       [5.71649, 4.38867, 3.76125],
       [4.84659, 4.569  , 4.39505]])

# ASE's traj

- See [ase.io module](https://wiki.fysik.dtu.dk/ase/ase/io/io.html)
- See [ase.io.trajectory module](https://wiki.fysik.dtu.dk/ase/ase/io/trajectory.html)
- See [ase.Atoms module](https://wiki.fysik.dtu.dk/ase/ase/atoms.html#module-ase.atoms)
  
The `ase.io.trajectory` module defines Trajectory objects, that is objects storing the *temporal evolution of a simulation* or *the path taken during an optimization*. A Trajectory file contains one or more `Atoms` objects, usually to be interpreted as a *time series*, although that is not a requirement.

Typically, trajectories are used to *store different configurations of the same system* (i.e. the same atoms). If you need to store configurations of different systems, the ASE `Database` module may be more appropriate.

Each configuration/frame in `traj` is an `Atoms` object, which have many useful methods and attributes. Read more [ase.Atoms module](https://wiki.fysik.dtu.dk/ase/ase/atoms.html#module-ase.atoms)
- get properties from `Atoms` object: `atoms.get_<prop>()`
- set properties fro `Atoms` object: `atoms.set_<prop>()`

In [ ]:
from glob import glob
from pathlib import Path

run_dir = globals()['_dh'][0]
path_drive = Path(run_dir.drive)

## Read a trajectory file
See [ase.io.trajectory module](https://wiki.fysik.dtu.dk/ase/ase/io/trajectory.html)

Read a trajectory file and extract its configurations. 

In [ ]:
path_base = Path(glob(run_dir.drive + "/*/w23_data_simulation/w24_ML_forcefield")[0])

dir1 = "test_gpaw/gpaw_MD"
path_data = path_base / dir1
os.chdir(path_data)  # noqa: F821


In [ ]:
from ase.io import Trajectory

traj = Trajectory('test_Cu.traj')
atoms = traj[-1]       # Atoms object of the last frame

In [ ]:
atoms

Atoms(symbols='Cu108', pbc=True, cell=[10.83, 10.83, 10.83], momenta=..., calculator=SinglePointCalculator(...))

In [ ]:
sub_traj = traj[0:None:2]  # every 10th frame

print(len(sub_traj))
print(len(traj))

26
51


In [ ]:
for i, atoms in enumerate(sub_traj):
    print(i, atoms.get_potential_energy())

0 -0.6136032267264113
1 1.7849176105338955
2 2.080027458235371
3 2.406602205055128
4 2.716029266247027
5 3.1452165195211563
6 3.134914564859841
7 3.1487996320502187
8 3.0431062211602224
9 3.2727029420128293
10 3.005454483702211
11 3.5434112961443542
12 3.2153518302609125
13 3.5302338042539194
14 3.707623858995177
15 3.5671555443432297
16 3.0912454993004737
17 3.153154274856803
18 3.5005412065752424
19 3.1754564035595543
20 3.1251069350775342
21 3.1762046560849537
22 3.5440777353486013
23 3.6137926271899588
24 3.7149064499086553


In [ ]:
atoms.get_stress()

array([ 1.04627525e-03,  2.50077709e-03,  2.42427384e-03, -2.61712152e-05,
        8.45425295e-04,  1.18892896e-03])

In [ ]:
atoms.get_forces()

array([[-0.50806878,  0.30226568,  0.49875246],
       [-0.1365271 ,  0.67894764,  0.16967721],
       [-0.28381146,  0.27952161,  0.23636692],
       [-0.09502838, -0.67566071,  0.12563425],
       [ 0.31291423, -0.33349539, -0.51868609],
       [ 0.90749486, -0.51285843, -0.07458926],
       [ 0.88831054,  0.13712637, -0.09671952],
       [-0.28270272, -0.17541964, -0.08961239],
       [-0.17987458,  0.51985437, -0.50096336],
       [ 0.01758714,  0.15160398, -0.24373048],
       [ 0.85029148, -0.15420802,  0.43599679],
       [ 0.08941008,  0.52576733, -0.32608561],
       [ 0.57156963,  0.02555867, -0.37101979],
       [-0.13871572,  0.29356718,  0.42694507],
       [-0.72999886, -0.42106963, -0.25658694],
       [ 0.10439868, -0.52994117, -0.11345909],
       [-0.2736142 ,  0.0835292 ,  0.74084367],
       [ 0.49835024,  0.13623765, -0.34504084],
       [-0.34018606,  0.0623103 ,  0.95428177],
       [-0.32840858,  0.39505034,  0.04811514],
       [ 0.22488496, -0.45522456, -0.570

In [ ]:
from ase.io import Trajectory, write

atoms = traj[0:3]
write('Cu.traj', atoms)

## Atoms object's attributes

In [ ]:
atoms.cell

Cell([10.83, 10.83, 10.83])

In [ ]:
atoms.positions

array([[-0.81769731, -0.28197442,  0.08458239],
       [ 0.94452629,  1.52457935,  0.19319378],
       [ 0.9444795 , -0.35651292,  1.95214602],
       [-0.79837699,  1.56452824,  1.93274131],
       [ 2.6454966 , -0.22642842,  0.21147916],
       [ 4.37893701,  1.59588798,  0.16937525],
       [ 4.39553674, -0.27010024,  1.98007876],
       [ 2.70786716,  1.62292541,  1.99653306],
       [ 6.28212772, -0.29758389,  0.19465168],
       [ 8.14683258,  1.43927092,  0.11520294],
       [ 8.08881227, -0.2120837 ,  1.95538078],
       [ 6.29194827,  1.40189638,  2.00238948],
       [-0.8703265 ,  3.35499006,  0.21306649],
       [ 0.92987577,  5.13775998,  0.11826851],
       [ 1.00383294,  3.45449226,  2.03861884],
       [-0.9052751 ,  5.23250684,  1.95927921],
       [ 2.71501452,  3.3963951 ,  0.1196628 ],
       [ 4.47880448,  5.20302931,  0.21891148],
       [ 4.58293338,  3.36660079,  1.83292948],
       [ 2.76809027,  5.09590479,  2.00040966],
       [ 6.33846796,  3.38200189,  0.249

## Atoms object's methods

In [ ]:
atoms.get_forces()

array([[-0.50806878,  0.30226568,  0.49875246],
       [-0.1365271 ,  0.67894764,  0.16967721],
       [-0.28381146,  0.27952161,  0.23636692],
       [-0.09502838, -0.67566071,  0.12563425],
       [ 0.31291423, -0.33349539, -0.51868609],
       [ 0.90749486, -0.51285843, -0.07458926],
       [ 0.88831054,  0.13712637, -0.09671952],
       [-0.28270272, -0.17541964, -0.08961239],
       [-0.17987458,  0.51985437, -0.50096336],
       [ 0.01758714,  0.15160398, -0.24373048],
       [ 0.85029148, -0.15420802,  0.43599679],
       [ 0.08941008,  0.52576733, -0.32608561],
       [ 0.57156963,  0.02555867, -0.37101979],
       [-0.13871572,  0.29356718,  0.42694507],
       [-0.72999886, -0.42106963, -0.25658694],
       [ 0.10439868, -0.52994117, -0.11345909],
       [-0.2736142 ,  0.0835292 ,  0.74084367],
       [ 0.49835024,  0.13623765, -0.34504084],
       [-0.34018606,  0.0623103 ,  0.95428177],
       [-0.32840858,  0.39505034,  0.04811514],
       [ 0.22488496, -0.45522456, -0.570

In [ ]:
atoms.get_velocities()

array([[-7.93373818e-03, -1.23641938e-02,  3.83552823e-03],
       [ 2.52393047e-04, -1.78510645e-03, -3.07393599e-02],
       [ 8.48075041e-03,  2.78844271e-02, -4.44871710e-02],
       [-2.82249718e-02, -3.16518934e-02, -2.57211605e-02],
       [ 2.62925615e-02,  7.18781612e-02,  3.54784799e-03],
       [ 2.12331131e-02,  5.38611877e-03,  1.63548344e-02],
       [-2.00962581e-02, -1.15813077e-02,  9.15138390e-04],
       [-3.93612793e-02, -3.91655554e-02,  3.21461500e-02],
       [-2.24946747e-03, -1.20597514e-03, -2.20499915e-02],
       [-4.18819448e-02,  1.04886588e-02, -2.50724627e-02],
       [ 3.32710566e-02,  4.82970216e-03, -4.80774148e-02],
       [ 1.12978136e-02,  1.22465566e-02,  2.33882698e-02],
       [-2.09814558e-02, -2.89730821e-03,  3.16252580e-02],
       [ 3.04788313e-03,  1.05321036e-02,  1.53552582e-02],
       [ 6.87100006e-03, -4.12346470e-03,  4.02582323e-02],
       [-8.46864957e-03, -9.28289106e-03,  5.70873571e-03],
       [ 3.33431158e-02, -1.43480876e-02

## Write/generate a trajectory file

Writing every 100th time step in a molecular dynamics simulation

In [ ]:
dyn = ()

# dyn is the dynamics (e.g. VelocityVerlet, Langevin or similar)
traj = Trajectory('example.traj', 'w', atoms)
dyn.attach(traj.write, interval=100)
dyn.run(10000)
traj.close()

## Convert `traj` to other formats
can convert to other [formats](https://wiki.fysik.dtu.dk/ase/ase/io/io.html) that can be used in Ovito

In [ ]:
from ase.io import Trajectory, write

traj = Trajectory('test_Cu.traj')
write("test_Cu.xyz", traj)
write("test_Cu.pdb", traj)

# extXYZ format

## Save `traj` in `extxyz` format
`extxyz` format is more flexible than `traj` format, when it *can be read by `Ovito`* and text editors. It is implemented in `ase/io/extxyz.py`

By default, `ase` will save *all available properties* to `extxyz` file. So should select properties to write
```python
atoms.write('file.extXYZ', format='extxyz', append=True)
```

```
32
Lattice="7.22 0.0 0.0 0.0 7.22 0.0 0.0 0.0 7.22" Properties=species:S:1:pos:R:3:momenta:R:3:energies:R:1:forces:R:3 energy=-0.18180836347449159 free_energy=-0.18180836347449159 stress="0.013619265229935899 -9.450819985549072e-19 1.2375555454051564e-17 -9.450819985549072e-19 0.013619265229935843 -5.2875592376782627e-17 1.2375555454051564e-17 -5.2875592376782627e-17 0.013619265229935937" pbc="T T T"
Cu       0.00000000       0.00000000       0.00000000      -0.40253488      -0.47185762       0.76847769      -0.00568151       0.00000000       0.00000000       0.00000000
```

In [ ]:
dyn = ()
### Traj in eXYZ format
def write_xyz(a=atoms):
    cols = [key for key in atoms.arrays if key not in ['symbols', 'positions', 'numbers', 'species', 'pos']]
    write("test_Cu.exyz", a, format="extxyz", append=True, columns=cols)

dyn.attach(write_xyz, interval=20)
dyn.run(100)

## Save `traj` and properties during MD simulation

In [ ]:
import os

from ase.io import paropen, write

dyn = ()

def print_properties(a=atoms, filename="output_properties.txt"):
    """Function to print the potential, kinetic and total energy"""
    ### Extract properties
    step = dyn.nsteps
    epot = a.get_potential_energy() / len(a)
    ekin = a.get_kinetic_energy() / len(a)
    energy = epot + ekin

    ### Write the header line
    if not os.path.exists(filename):
        with paropen(filename, "w") as fo:
            fo.write("step energy epot ekin\n")

    ### Append the data to the file
    with paropen(filename, "a") as fo:
        fo.write(f"{step} {energy:.7f} {epot:.7f} {ekin:.7f}\n")

    ### Print the energy to the screen
    # print(
    #     f"Energy per atom (eV): Epot={epot:.7f}  Ekin={ekin:.7f} Etot={energy:.7f}"
    # )


### Traj in eXYZ format
def write_xyz(a=atoms):
    write("test_Cu.exyz", a, format="extxyz", append=True)


dyn.attach(print_properties, interval=10)
dyn.attach(write_xyz, interval=20)

### Save the trajectory
traj = Trajectory("test_Cu.traj", "w", atoms)
dyn.attach(traj.write, interval=20)


dyn.run(100)

## Read/write `extxyz` file
Normally, `atoms` saves properties in:
- `atoms.arrays`: a dictionary containing array-like data (both internal/custom keys), such as: `positions`, `id`, `type`,...
- `atoms.info`: a dictionary containing metadata data, general data, or custom-key properites, such as: `timestep`, `custom_stress`
- `atoms.calc.results`: a dictionary containing results from calculations if `extxyz` contains *ASE's internal-keys*,  such as: `energy`, `forces`, `stress`, `free_energy`,...
- `atoms.pbc`: a boolean array indicating periodic boundary conditions (PBC) for each dimension
> Should use internal-keys for properties, and access them via `atoms.calc.results`. Using `atoms.arrays` and `atoms.info` to access other/custom properties.

- See more with: 
    ```py
    atoms.__dict__
    atoms.calc.__dict__
    atoms.arrays.keys()
    atoms.info.keys()
    ```

1. `extxyz` with ASE's internal keys
When reading Atoms object that contains *reversed keys*, such as: `energy`, `forces`, `stress`, `momenta`, `free_energy`,... there will has a `SinglePointCalculator` object included in the Atoms, and these keys can be accessed via `atoms.calc.results` or using `.get_()` methods. See [this issue](https://gitlab.com/ase/ase/-/merge_requests/3226/diffs)

2. Stress in `extxyz`
    - *internal-key* `stress` is always read/written in 3x3 format (1x9 format). But, *custom-key* `custom_stress` is always read/written in 1x6 format.
    - `.get_stress()` always returns in 1x6 format. It means `atoms.calc.results['stress']` is always returned in 1x6 format.
    - When read `extxyz`, `stress` is returned in *Voigt notation* (1x6 format).

### Read internal-keys
Example with internal keys, note that:
- internal-key `stress` is written in 1x9 format
- There is a dict `atoms.calc.results` that contains internal-keys: `energy`, `forces`, `stress`

In [6]:
### extxyz with internal keys (note: stress in 1x9 format)
from ase.io import read

atoms = read("test_file/extxyz/conf_keys_internal.extxyz", format="extxyz", index=0)
atoms

Atoms(symbols='MoS2', pbc=True, cell=[[6.685222733778327, 0.0, 0.0], [-3.3426113668891637, 5.5138787789308825, 0.0], [0.0, 0.0, 6.16628910792779]], momenta=..., calculator=SinglePointCalculator(...))

In [7]:
atoms.arrays

{'numbers': array([42, 16, 16]),
 'positions': array([[0.        , 0.        , 3.08314455],
        [1.67132121, 0.91898834, 4.66194359],
        [0.        , 1.83797668, 1.50434552]]),
 'momenta': array([[-0.48178956,  3.18459932,  0.14035658],
        [-0.46677606, -2.00063308, -2.35378966],
        [-0.91708756,  2.72938297,  1.14097786]])}

In [8]:
atoms.info

{'timestep': np.int64(10)}

In [9]:
atoms.calc.results

{'forces': array([[-2.0000000e-08, -4.0000000e-08,  6.0000000e-08],
        [-2.1922300e-03, -1.8431043e-01, -5.0839116e-01],
        [ 2.3996100e-03,  1.8455348e-01,  5.0845134e-01]]),
 'stress': array([6.40010816e-02, 1.06032953e-02, 3.39326081e-02, 1.13827447e-02,
        6.23480654e-05, 1.89601052e-04]),
 'energy': np.float64(-87.50511672376267)}

In [37]:
atoms.calc.results["stress"]

array([-0.0021653 , -0.00213299,  0.        ,  0.        ,  0.        ,
       -0.00114498])

In [ ]:
atoms.get_stress()

### Read custom-keys
Example with customs keys, and note that:
- `ref_stress` is written 1x6 format
- There is no dict `atoms.calc.results`, but custom-keys properties are stored in `atoms.info` and `atoms.arrays`
    - `atoms.info` contains `ref_stress`, `ref_energy`
    - `atoms.arrays` contains `ref_forces`
- can not use `.get_stress()` to get `ref_stress` as it is not an internal key.

In [39]:
### extxyz with custom keys (note: stress in 1x6 format)
from ase.io import read

atoms = read("test_file/extxyz/conf_keys_custom.extxyz", format="extxyz", index=0)
atoms

Atoms(symbols='MoTe2', pbc=True, cell=[[7.032058291507576, 0.0, 0.0], [-3.5160291457537887, 6.089964484499853, 0.0], [0.0, 0.0, 36.59]], ref_forces=...)

In [30]:
atoms.arrays

{'numbers': array([42, 52, 52]),
 'positions': array([[-0.137009,  0.99227 , 18.1903  ],
        [ 1.69605 ,  1.98513 , 20.0301  ],
        [ 1.70674 ,  2.0696  , 16.4726  ]]),
 'ref_forces': array([[ 0.69656149,  0.43770026,  0.67974643],
        [-1.03895799,  0.90736254,  0.50629235],
        [-0.39642844,  0.16426686, -0.34999382]])}

In [34]:
atoms.info

{'ref_stress': array([-0.0021653 , -0.00165225, -0.00155256, -0.00114498, -0.00213299,
         0.00058895]),
 'ref_energy': np.float64(-75.17089920500057),
 'timestep': np.int64(10)}

In [35]:
atoms.calc.results

AttributeError: 'NoneType' object has no attribute 'results'

In [40]:
atoms.get_stress()

RuntimeError: Atoms object has no calculator.

In [ ]:
atoms.pbc

array([ True,  True,  True])

### Package `alff`

In [ ]:
from alff.gdata.util_dataset import change_key_in_extxyz

### Change internal-keys to custom-keys
change_key_in_extxyz(
    "test_file/extxyz/conf_changekeys.extxyz",
    {"forces": "ref_forces", "stress": "ref_stress", "energy": "ref_energy"},
)
atoms = read("test_file/extxyz/conf_changekeys.extxyz", format="extxyz", index=0)
atoms.info["ref_stress"] # must be 1x6 format

/home/tha/app/miniforge/envs/py13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


array([-0.0021653 , -0.00213299,  0.        ,  0.        ,  0.        ,
       -0.00114498])

In [5]:
### Change custom-keys to internal-keys
change_key_in_extxyz(
    "test_file/extxyz/conf_changekeys.extxyz",
    {"ref_forces": "forces", "ref_stress": "stress", "ref_energy": "energy"},
)
atoms = read("test_file/extxyz/conf_changekeys.extxyz", format="extxyz", index=0)
atoms.calc.results["stress"]  # must be 1x9 format

array([-0.0021653 , -0.00213299,  0.        ,  0.        ,  0.        ,
       -0.00114498])

# extXYZ to lammps_DATA
IMPORTANT NOTE:
- When use `ase.write` to write `lammps-data` format, the `cell` (and all vector quantities) will change their orirentation. Due to *LAMMPS required a specific form* of the `cell` (called *retricted triclinic box*): 
    ```py
    [[ ax, 0, 0 ]
    [ bx, by, 0 ]
    [ cx, cy, cz ]]
    ```
    -  In ASE, this cell in the form of a [*lower triangular matrix*](https://gitlab.com/ase/ase/-/issues/1349), note that ASE-NPT class requires the cell to be in the form of an *upper triangular matrix*, see this [issue](https://gitlab.com/ase/ase/-/merge_requests/3277#note_2255046877).

- Therefore, to convert back (all calculated vector quantities in LAMMPS) to original orientation, need to save the original `ase_cell` *before write lammps-data*.
    ```py
    from ase.calculators.lammps import Prism
    ori_cell = atoms.cell.copy()
    ```
    Now, assume after wrting `lammps_data` file, we want to convert back to original orientation before rotated by `ase.write`:
    ```py
    write_lammps_data("test_file/conf2.lmpdata", atoms)
    atoms = read('file.lammps_data')
    p = Prism(ori_cell)
    positions = p.vector_to_ase(atoms.positions)
    cell = p.vector_to_ase(atom.cell)
    ```
- If before writing `lammps_data`, the `cell` is already in the *retricted triclinic box* form (or upper triangular matrix), then writing no change the `cell` orientation. See example below for more detail. This give a trick to create structure in ASE: 
    - Need to write `lammps_data` first, then read back to ASE to get the `cell` in the *retricted triclinic box* form (#NOTE: This method only write `cell` and `positions`, and remove other properties). Or use [this function](https://github.com/thangckt/alff/blob/dev/alff/util/ase_struct.py#L94). 

Example: Write `lammps_data` file, and read it back to Atoms object to see the properties is rotated in lammps_data file.

In [13]:
from ase.build import bulk
from ase.io import read, write
from ase.io.lammpsdata import write_lammps_data

atoms = bulk("Si", crystalstructure="diamond", a=5.43)
### Original cell
print("Original Positions: \n", atoms.positions)
print("\nOriginal cell: \n", atoms.cell.array)

### write to lammmps_data and read back
write_lammps_data("test_file/conf.lmpdata", atoms, atom_style="atomic", masses=True)
atoms = read("test_file/conf.lmpdata", format="lammps-data")

### Changed cell
print("\nRotated Positions: \n", atoms.positions)
print("\nRotated cell: \n", atoms.cell.array)

Original Positions: 
 [[0.     0.     0.    ]
 [1.3575 1.3575 1.3575]]

Original cell: 
 [[0.    2.715 2.715]
 [2.715 0.    2.715]
 [2.715 2.715 0.   ]]

Rotated Positions: 
 [[0.         0.         0.        ]
 [1.91979491 1.10839411 0.78375299]]

Rotated cell: 
 [[3.83958982 0.         0.        ]
 [1.91979491 3.32518233 0.        ]
 [1.91979491 1.10839411 3.13501196]]


Now, write again to see what happens:

In [14]:
### write again
write_lammps_data("test_file/conf2.lmpdata", atoms, atom_style="atomic", masses=True)
atoms = read("test_file/conf2.lmpdata", format="lammps-data")

### Print cell
print("\nRotated Positions: \n", atoms.positions)
print("\nRotated cell: \n", atoms.cell.array)


Rotated Positions: 
 [[0.         0.         0.        ]
 [1.91979491 1.10839411 0.78375299]]

Rotated cell: 
 [[3.83958982 0.         0.        ]
 [1.91979491 3.32518233 0.        ]
 [1.91979491 1.10839411 3.13501196]]


Way2: Use `alff.util.ase_struct` to convert `cell` to the *retricted triclinic box* form. 

In [ ]:
from asext.struct import make_cell_upper_triangular
from ase.build import bulk

atoms = bulk("Si", crystalstructure="diamond", a=5.43)
### Original cell
print("Original Positions: \n", atoms.positions)
print("\nOriginal cell: \n", atoms.cell.array)

### Changed cell
atoms = make_cell_upper_triangular(atoms)
print("\nRotated Positions: \n", atoms.positions)
print("\nRotated cell: \n", atoms.cell.array)

Original Positions: 
 [[0.     0.     0.    ]
 [1.3575 1.3575 1.3575]]

Original cell: 
 [[0.    2.715 2.715]
 [2.715 0.    2.715]
 [2.715 2.715 0.   ]]

Rotated Positions: 
 [[ 0.          0.          0.        ]
 [ 0.78375299  1.10839411 -1.91979491]]

Rotated cell: 
 [[ 3.13501196  1.10839411 -1.91979491]
 [ 0.          3.32518233 -1.91979491]
 [ 0.          0.         -3.83958982]]


In [ ]:
### make lower triangular to use in LAMMPS
from asext.struct import make_cell_lower_triangular
from ase.build import bulk

atoms = bulk("Si", crystalstructure="diamond", a=5.43)
### Original cell
print("Original Positions: \n", atoms.positions)
print("\nOriginal cell: \n", atoms.cell.array)

### Changed cell
atoms = make_cell_lower_triangular(atoms)
print("\nRotated Positions: \n", atoms.positions)
print("\nRotated cell: \n", atoms.cell.array)

Original Positions: 
 [[0.     0.     0.    ]
 [1.3575 1.3575 1.3575]]

Original cell: 
 [[0.    2.715 2.715]
 [2.715 0.    2.715]
 [2.715 2.715 0.   ]]

Rotated Positions: 
 [[0.         0.         0.        ]
 [1.91979491 1.10839411 0.78375299]]

Rotated cell: 
 [[ 3.83958982  0.         -0.        ]
 [ 1.91979491  3.32518233 -0.        ]
 [ 1.91979491  1.10839411  3.13501196]]


c:\DevProgram\miniconda\envs\py11\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## test

In [ ]:
# test
import numpy as np
from ase.build import bulk

atoms = bulk("Si", crystalstructure="diamond", a=5.43)

atoms.cell

Cell([[0.0, 2.715, 2.715], [2.715, 0.0, 2.715], [2.715, 2.715, 0.0]])

In [14]:
modified_cell = atoms.cell.array.copy()  # Ensure we don't modify the original directly
modified_cell[modified_cell < 2] = 0
atoms.set_cell(modified_cell, strain_atoms=True)
atoms.cell

Cell([[0.0, 2.715, 2.715], [2.715, 0.0, 2.715], [2.715, 2.715, 0.0]])

Try this change and check if the final atomic cell remains correct.
Compare the initial and final volumes:

In [ ]:
print("Initial volume:", np.linalg.det(input_atoms.cell)) # noqa: F821
print("Final volume:", np.linalg.det(atoms.cell))

In [8]:
modified_cell

0

## Save original orientation
See functions in this file: https://gitlab.com/ase/ase/-/blob/5b52f1471c13d1a6578ee2ae0c5be95d1bf6adf8/ase/calculators/lammps/coordinatetransform.py
- dicussed in this [issue](https://gitlab.com/ase/ase/-/issues/1571)


In [ ]:
atoms = bulk("Si", crystalstructure="diamond", a=5.43)
ori_cell = atoms.cell.copy()
print(atoms.positions)
print(atoms.cell)

[[0.     0.     0.    ]
 [1.3575 1.3575 1.3575]]
Cell([[0.0, 2.715, 2.715], [2.715, 0.0, 2.715], [2.715, 2.715, 0.0]])


In [50]:
### write lammmps data
write_lammps_data("test_file/conf.lmpdata", atoms, atom_style="atomic", masses=True)
atoms = read("test_file/conf.lmpdata", format="lammps-data")
print(atoms.positions)
print(atoms.cell)

[[0.     0.     0.    ]
 [1.3575 1.3575 1.3575]]
Cell([[3.839589821842953, 0.0, 0.0], [1.9197949109214762, 3.325182325828164, 0.0], [1.9197949109214762, 1.1083941086093883, 3.135011961699668]])


In [49]:
atoms.arrays

{'numbers': array([14, 14]),
 'positions': array([[0.    , 0.    , 0.    ],
        [1.3575, 1.3575, 1.3575]]),
 'masses': array([28.085, 28.085]),
 'id': array([1, 2]),
 'type': array([1, 1])}

In [ ]:
from ase.calculators.lammps import Prism

p = Prism(ori_cell)
### Recover the original cell
orginal_cell = p.vector_to_ase(atoms.cell)
atoms.positions = p.vector_to_ase(atoms.positions)

print(atoms.positions)
print(orginal_cell)

[[0.     0.     0.    ]
 [1.3575 1.3575 1.3575]]
[[0.    2.715 2.715]
 [2.715 0.    2.715]
 [2.715 2.715 0.   ]]


## Write `atom_types` in `lammps_data`
`2025Sep24`, current ASE can not allow custom `atom_types` when convert from `extxyz` to `lammpsdata` file. 

Workaround:
1. Use `write_lammps_data` function with `specorder` argument write `masses` section with expected `types`
2. Then manually set types in LAMMPS using 
```sh
set atom <ids> type <type>
```
Note: to auto convert between `extxyz` and `lammps_data`, must save `atoms.info['specorder']` before write `extxyz`, and read it back after read `extxyz`. 

In [ ]:
from ase.build import mx2
from ase.io.lammpsdata import write_lammps_data

struct = mx2(formula="MoS2", kind="2H", a=3.18, thickness=3.17, size=(1, 1, 1), vacuum=5)

### Write masses section with specorder coressponding to atom types
specorder = ["S", "Mo", "S"]
write_lammps_data("test.lmpdata", struct, atom_style="full", masses=True, specorder=specorder)

## `alff` package

In [ ]:
from asext.struct import extxyz2lmpdata

atom_names, pbc = extxyz2lmpdata(
    extxyz_file="test_file/MoSe2.extxyz",
    lmpdata_file="test_file/MoSe2.lmpdata",
    atom_style="atomic",
)

/home/tha/app/miniforge/envs/py13alff/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
atom_names

['Mo', 'Se']

In [3]:
pbc

[1, 1, 1]

## Convert stress 1x6 to 3x3
- Note: use a `SinglePointCalculator` so save stress with reserved key `stress`, then write to extXYZ file, stress always in 3x3 format.

In [ ]:
from ase.calculators.singlepoint import SinglePointCalculator
from ase.io import read
from ase.stress import voigt_6_to_full_3x3_stress

atoms = read("test_file/Mo_conf_label.extxyz", format="extxyz", index=0)
atoms

Atoms(symbols='Mo8', pbc=True, cell=[[-3.159883685019072, 3.1598836850189906, 3.159883685018965], [3.15988368501908, -3.159883685018971, 3.159883685018957], [3.159883685019086, 3.159883685018971, -3.159883685018957]], ref_forces=...)

In [2]:
atoms.info

{'ref_energy': -90.08853652890342,
 'ref_stress': array([ 1.33217330e-03,  1.33217330e-03,  1.33217330e-03, -1.11990212e-17,
        -6.63645698e-18, -6.63645698e-18])}

In [3]:
atoms.calc = SinglePointCalculator(atoms)
# atoms.calc.results["stress"] = voigt_6_to_full_3x3_stress(atoms.info["ref_stress"])
atoms.calc.results["stress"] = atoms.info["ref_stress"]

In [4]:
atoms.calc.results["stress"]

array([ 1.33217330e-03,  1.33217330e-03,  1.33217330e-03, -1.11990212e-17,
       -6.63645698e-18, -6.63645698e-18])

In [5]:
atoms.get_stress()

array([ 1.33217330e-03,  1.33217330e-03,  1.33217330e-03, -1.11990212e-17,
       -6.63645698e-18, -6.63645698e-18])

In [6]:
atoms.write("test_file/Mo_conf_label_test.extxyz", format="extxyz")

## Change keys in extXYZ file

In [ ]:
from alff.gdata.util_dataset import change_key_in_extxyz

### custom_keys to custom_keys
change_key_in_extxyz(
    "test_file/Mo_conf_label_test.extxyz", {"ref_stress": "ref2_stress"}
)

In [3]:
### reserved_keys to custom_keys
change_key_in_extxyz("test_file/Mo_conf_label_test.extxyz", {"stress": "ref_stress"})

In [2]:
### custom_keys to reserved_keys
change_key_in_extxyz("test_file/Mo_conf_label_test.extxyz", {"ref2_stress": "stress"})

## Read lammps DUMP
Convert `stress`, `forces`,... from LAMMPS to ASE format. 

Note: ASE do not save `type` of LAMMPS data.

See file: 
- `/ase/calculators/lammpslib.py/propagate()`
- `/ase/io/lammpsrun.py`

In [6]:
from ase.io import read

struct = read("test_file/struct_test.lmpdump", format="lammps-dump-text")

In [7]:
struct.pbc

array([ True,  True,  True])

In [8]:
(struct.calc.results).keys()

dict_keys(['energy', 'forces'])

In [9]:
struct.info

{'timestep': 3}

In [10]:
struct.arrays

{'numbers': array([29, 29, 29, 29, 29, 29, 29, 29]),
 'positions': array([[-3.74562e-06, -3.74562e-06, -3.74562e-06],
        [-3.74562e-06,  1.80750e+00,  1.80750e+00],
        [ 1.80750e+00, -3.74562e-06,  1.80750e+00],
        [ 1.80750e+00,  1.80750e+00, -3.74562e-06],
        [-3.74562e-06, -3.74562e-06,  3.61500e+00],
        [-3.74562e-06,  1.80750e+00,  5.42250e+00],
        [ 1.80750e+00, -3.74562e-06,  5.42250e+00],
        [ 1.80750e+00,  1.80750e+00,  3.61500e+00]])}

In [9]:
if not struct.calc:
    print("No calc found")

# Find unitcell from Supercell
Using package `spglib` to find the unitcell of a system. 
NOTE: must use `get_scaled_positions` to find the unitcell. 

In [26]:
import spglib

help(spglib.spglib)

Help on module spglib.spglib in spglib:

NAME
    spglib.spglib - Python bindings for C library for finding and handling crystal.

CLASSES
    builtins.object
        SpglibError
    collections.abc.Mapping(collections.abc.Collection)
        DictInterface
            MagneticSpaceGroupType
            SpaceGroupType
            SpglibDataset
            SpglibMagneticDataset
    
    class DictInterface(collections.abc.Mapping)
     |  DictInterface() -> None
     |  
     |  Base class for dataclass with dict interface.
     |  
     |  .. versionadded:: 2.5.0
     |  .. deprecated:: 2.5.0
     |      Dict-like interface (``obj['field']``) are deprecated.
     |      Please use attribute interface instead (``obj.field``)
     |  
     |  Method resolution order:
     |      DictInterface
     |      collections.abc.Mapping
     |      collections.abc.Collection
     |      collections.abc.Sized
     |      collections.abc.Iterable
     |      collections.abc.Container
     |      bui

In [32]:
from ase.build import bulk
from ase.io import read, write

atoms = bulk("Si", crystalstructure="diamond", a=5.43)
print(atoms.positions)
print(atoms.cell)

[[0.     0.     0.    ]
 [1.3575 1.3575 1.3575]]
Cell([[0.0, 2.715, 2.715], [2.715, 0.0, 2.715], [2.715, 2.715, 0.0]])


In [31]:
### Supercell
atoms1 = atoms.repeat((2, 2, 2))
print(atoms1.positions)
print(atoms1.cell)

[[0.     0.     0.    ]
 [1.3575 1.3575 1.3575]
 [2.715  2.715  0.    ]
 [4.0725 4.0725 1.3575]
 [2.715  0.     2.715 ]
 [4.0725 1.3575 4.0725]
 [5.43   2.715  2.715 ]
 [6.7875 4.0725 4.0725]
 [0.     2.715  2.715 ]
 [1.3575 4.0725 4.0725]
 [2.715  5.43   2.715 ]
 [4.0725 6.7875 4.0725]
 [2.715  2.715  5.43  ]
 [4.0725 4.0725 6.7875]
 [5.43   5.43   5.43  ]
 [6.7875 6.7875 6.7875]]
Cell([[0.0, 5.43, 5.43], [5.43, 0.0, 5.43], [5.43, 5.43, 0.0]])


In [ ]:
from ase import Atoms
from spglib import spglib

cell = (atoms1.cell, atoms1.get_scaled_positions(), atoms1.numbers)
primitive_cell = spglib.find_primitive(cell=cell, symprec=1e-5, angle_tolerance=-1.0)
primitive_cell

### Convert the primitive cell to ASE Atoms object
cell, positions, numbers = primitive_cell
primitive_atoms = Atoms(cell=cell, scaled_positions=positions, numbers=numbers)
primitive_atoms

Atoms(symbols='Si2', pbc=False, cell=[[0.0, 2.715, 2.715], [2.715, 0.0, 2.715], [2.715, 2.715, 0.0]])

In [33]:
primitive_atoms.positions

array([[0.    , 0.    , 0.    ],
       [1.3575, 1.3575, 1.3575]])

## Test with less symmetry system
Example structure is optimized by LAMMPS
- Use `symprec=1e-3`

In [4]:
from ase.io import read
from ase.visualize import view

atoms = read("test_file/conf_labeled_lessSym.extxyz", format="extxyz")
print(atoms.positions)
print(atoms.cell)
view(atoms)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.35802798e+00 1.35803085e+00 1.35803053e+00]
 [2.71605570e+00 2.71605857e+00 2.81000000e-06]
 [4.07408885e+00 4.07408473e+00 1.35803037e+00]
 [2.71605552e+00 2.93000000e-06 2.71605845e+00]
 [4.07408753e+00 1.35802794e+00 4.07408716e+00]
 [5.43211524e+00 2.71605565e+00 2.71605944e+00]
 [6.79014023e+00 4.07408589e+00 4.07408292e+00]
 [0.00000000e+00 2.71605755e+00 2.71605755e+00]
 [1.35802798e+00 4.07408457e+00 4.07408424e+00]
 [2.71605570e+00 5.43211228e+00 2.71605653e+00]
 [4.07408885e+00 6.79014551e+00 4.07409115e+00]
 [2.71605552e+00 2.71605664e+00 5.43211217e+00]
 [4.07408753e+00 4.07408872e+00 6.79014794e+00]
 [5.43211524e+00 5.43211644e+00 5.43212023e+00]
 [6.79014023e+00 6.79014668e+00 6.79014370e+00]]
Cell([[0.0, 5.432114844309289, 5.432114844309289], [5.432114844309286, 0.0, 5.432114844309286], [5.432114844309287, 5.432114844309288, 2.2626455141574916e-16]])


<Popen: returncode: None args: ['c:\\DevProgram\\miniconda3\\envs\\py11\\pyt...>

In [10]:
from ase import Atoms
from spglib import spglib

cell = (atoms.cell, atoms.get_scaled_positions(), atoms.numbers)
primitive_cell = spglib.find_primitive(cell=cell, symprec=1e-4, angle_tolerance=-1.0)

### Convert the primitive cell to ASE Atoms object
cell, positions, numbers = primitive_cell
primitive_atoms = Atoms(cell=cell, scaled_positions=positions, numbers=numbers)
print(primitive_atoms.positions)
print(primitive_atoms.cell)
view(primitive_atoms)

[[2.71605742 2.71605742 2.71605742]
 [4.07408613 4.07408613 4.07408613]]
Cell([[0.0, 2.7160574221546434, 2.7160574221546434], [2.7160574221546434, 0.0, 2.7160574221546434], [2.7160574221546434, 2.7160574221546434, 0.0]])


<Popen: returncode: None args: ['c:\\DevProgram\\miniconda3\\envs\\py11\\pyt...>