In [4]:
# ! pip install git+https://gitlab.com/ase/ase@master
# ! pip install ase

In [ ]:
run_dir = globals()["_dh"][0]

# Create the `Atoms` object
The `Atoms` object have many useful methods and attributes. Read more [`ase.Atoms` module](https://wiki.fysik.dtu.dk/ase/ase/atoms.html#module-ase.atoms)
- get properties from `Atoms` object: `atoms.get_<prop>()`
- set properties for `Atoms` object: `atoms.set_<prop>()`

ASE support many way to build models, such as
- bulk
- molecule
- surface
- nanotube
- ... See more in [`ase.build`](https://wiki.fysik.dtu.dk/ase/ase/build/build.html)

REF:
- See [`ase.build`](https://wiki.fysik.dtu.dk/ase/ase/build/build.html)
- See [`ase.Atoms`](https://wiki.fysik.dtu.dk/ase/ase/atoms.html#module-ase.atoms)

## Build Atoms
Create the [`ase.Atoms`](https://wiki.fysik.dtu.dk/ase/ase/atoms.html#module-ase.atoms) object

In [2]:
from ase import Atoms

d = 2.9
L = 10.0
atoms = Atoms('Au',
              positions=[[0, L / 2, L / 2]],
              cell=[d, L, L],
              pbc=[1, 0, 0])

## Build models

### build `molecule`
Create `molecule` using `ase.build.molecule`

In [18]:
from ase.build import molecule

atoms = molecule('CH4')
atoms.center(vacuum=4.0)

In [19]:
symbol = atoms.get_chemical_symbols()
symbol

['C', 'H', 'H', 'H', 'H']

In [20]:
s = set(symbol)
s

{'C', 'H'}

In [22]:
## This will change the order of the elements
list(s)

['H', 'C']

In [9]:
## Use this to maintain the order
s = list(dict.fromkeys(symbol))
s

['C', 'H']

In [10]:
dict.fromkeys(symbol)

{'C': None, 'H': None}

In [12]:
atoms.get_masses()

array([12.011,  1.008,  1.008,  1.008,  1.008])

In [17]:
atoms.symbols

Symbols('CH4')

### Build `bulk`
Create `bulk` models using `ase.build.bulk`

In [3]:
from ase.build import bulk
from ase.visualize import view

a1 = bulk("Cu", "fcc")
a2 = bulk("Cu", "fcc", orthorhombic=True)
a3 = bulk("Cu", "fcc", cubic=True)
view(a3)

<Popen: returncode: None args: ['/home/tha/app/miniforge/envs/py13/bin/pytho...>

### Build `surface`
Build [surfaces](https://wiki.fysik.dtu.dk/ase/ase/build/surface.html#ase.build.mx2) 

Using `ase.build.surface` to build non-common surfaces

### Build `MX2`

In [4]:
from ase.build import mx2

atoms = mx2(formula="MoS2", kind="2H", a=3.18, thickness=3.19, size=(3, 3, 1), vacuum=None)
view(atoms)

<Popen: returncode: None args: ['/home/tha/app/miniforge/envs/py13/bin/pytho...>

### Build `graphene`
Note: in func `build.graphene()` does have the vector c of the cell. So, to model 3d box or Graphite, we need to manually add 3rd vector to the cell.
- Build with `thickness=0.0` 
- Then add the 3rd vector to the cell

In [10]:
from ase.build import graphene

struct = graphene(formula="C2", a=2.46, thickness=0.0, size=(3, 3, 1), vacuum=None)
view(struct)

<Popen: returncode: None args: ['/home/tha/app/miniforge/envs/py13/bin/pytho...>

In [13]:
### Add thickness to the cell
c = struct.cell
c[2, 2] = 3.5
struct.set_cell(c)
struct.center()
view(struct)

<Popen: returncode: None args: ['/home/tha/app/miniforge/envs/py13/bin/pytho...>

In [5]:
help(graphene)

Help on function graphene in module ase.build.surface:

graphene(formula='C2', a=2.46, thickness=0.0, size=(1, 1, 1), vacuum=None)
    Create a graphene monolayer structure.

    Parameters
    ----------
    thickness : float, default: 0.0
        Thickness of the layer; maybe for a buckled structure like silicene.



## General 3D mat
Build 3D mat using [`ase.lattice.BravaisLattice`](https://wiki.fysik.dtu.dk/ase/ase/lattice.html#module-ase.lattice)
- Bravais lattice objects, which represent primitive cells and Brillouin zone information which is useful for calculating band structures
- A general framework for building Atoms objects based Bravais lattice and basis

There are 14 3D Bravais classes: CUB, FCC, BCC, …, and TRI, and five 2D classes.

### Crystal structures

In [19]:
from ase.lattice.cubic import FaceCenteredCubic
from ase.visualize import view

atoms = FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
                          size=(3,3,3), symbol='Cu', pbc=(1,1,0))
view(atoms)

<Popen: returncode: None args: ['c:\\DevProgram\\miniconda3\\envs\\py11\\pyt...>

In [31]:
from ase.lattice.cubic import BodyCenteredCubic

atoms = BodyCenteredCubic(directions=[[1,0,0], [0,1,0], [1,1,1]],
                          size=(2,2,3), symbol='Cu', pbc=(1,1,0),
                          latticeconstant=4.0)
view(atoms)

<Popen: returncode: None args: ['c:\\DevProgram\\miniconda3\\envs\\py11\\pyt...>

### Brillouin zone information
Bravais lattice objects, which represent primitive cells and Brillouin zone information which is useful for calculating band structures

In [12]:
from ase.lattice import FCC

FCC.parameters

('a',)

In [28]:
FCC(2).bandpath()

BandPath(path='GXWKGLUWLK,UX', cell=[3x3], special_points={GKLUWX}, kpts=[101x3])

# Atoms's methods
- See: https://wiki.fysik.dtu.dk/ase/ase/atoms.html#list-of-all-methods

## Count atoms

In [2]:
from ase.build import mx2
from ase.visualize import view

struct = mx2(formula="MoS2", kind="2H", a=3.18, thickness=3.19, size=(3, 3, 1), vacuum=5)
struct.symbols.count("Mo")
view(struct)

<Popen: returncode: None args: ['/home/tha/app/miniforge/envs/py13/bin/pytho...>

In [ ]:
struct.symbols.formula.count()

{'Mo': 9, 'S': 18}

In [ ]:
struct.symbols.formula.format("ab2")

'Mo9S18'

In [ ]:
struct.get_chemical_formula()

'Mo9S18'

In [ ]:
# help(struct.symbols.formula)
help(struct)

Help on Atoms in module ase.atoms object:

class Atoms(builtins.object)
 |  Atoms(
 |      symbols=None,
 |      positions=None,
 |      numbers=None,
 |      tags=None,
 |      momenta=None,
 |      masses=None,
 |      magmoms=None,
 |      charges=None,
 |      scaled_positions=None,
 |      cell=None,
 |      pbc=None,
 |      celldisp=None,
 |      constraint=None,
 |      calculator=None,
 |      info=None,
 |      velocities=None
 |  )
 |
 |  Atoms object.
 |
 |  The Atoms object can represent an isolated molecule, or a
 |  periodically repeated structure.  It has a unit cell and
 |  there may be periodic boundary conditions along any of the three
 |  unit cell axes.
 |  Information about the atoms (atomic numbers and position) is
 |  stored in ndarrays.  Optionally, there can be information about
 |  tags, momenta, masses, magnetic moments and charges.
 |
 |  In order to calculate energies, forces and stresses, a calculator
 |  object has to attached to the atoms object.
 |
 | 

## Select atoms

In [ ]:
### filter atoms by symbol
elements = struct.get_chemical_symbols()
# elements
tmp_idxs = [i for i, e in enumerate(elements) if e == "Mo"]
tmp_idxs

[0, 3, 6, 9, 12, 15, 18, 21, 24]

In [18]:
struct.positions

array([[ 0.        ,  0.        ,  0.        ],
       [ 1.59      ,  0.91798693,  1.595     ],
       [ 1.59      ,  0.91798693, -1.595     ],
       [-1.59      ,  2.75396078,  0.        ],
       [ 0.        ,  3.67194771,  1.595     ],
       [ 0.        ,  3.67194771, -1.595     ],
       [-3.18      ,  5.50792157,  0.        ],
       [-1.59      ,  6.4259085 ,  1.595     ],
       [-1.59      ,  6.4259085 , -1.595     ],
       [ 3.18      ,  0.        ,  0.        ],
       [ 4.77      ,  0.91798693,  1.595     ],
       [ 4.77      ,  0.91798693, -1.595     ],
       [ 1.59      ,  2.75396078,  0.        ],
       [ 3.18      ,  3.67194771,  1.595     ],
       [ 3.18      ,  3.67194771, -1.595     ],
       [ 0.        ,  5.50792157,  0.        ],
       [ 1.59      ,  6.4259085 ,  1.595     ],
       [ 1.59      ,  6.4259085 , -1.595     ],
       [ 6.36      ,  0.        ,  0.        ],
       [ 7.95      ,  0.91798693,  1.595     ],
       [ 7.95      ,  0.91798693, -1.595

In [17]:
struct.symbols.count()

TypeError: Sequence.count() missing 1 required positional argument: 'value'

# Compute properties
Note that, 
- no GPAW for Windows -> use WSL
- `stress` only available when using mode = `PW`
- `atoms.get_potential_energies()`: compute per-atom energies, Only available with calculators supporting per-atom energies (e.g. classical potentials).

## Write properties to traj

In [1]:
from ase import Atoms

d = 2.9
L = 10.0
atoms = Atoms('Au',
              positions=[[0, L / 2, L / 2]],
              cell=[d, L, L],
              pbc=[1, 1, 1])

In [2]:
atoms.get_forces()

RuntimeError: Atoms object has no calculator.

In [27]:
from ase.calculators.calculator import PropertyNotImplementedError
from ase.io import Trajectory, write
from gpaw import GPAW, PW

calc = GPAW(mode=PW(300),
            xc='PBE',
            txt='calc.txt')

##### attach calculator
atoms.calc = calc

##### compute properties
atoms.get_potential_energy()
atoms.get_forces()

### compute stress only if the calculator supports it
try:
    atoms.get_stress(voigt=False)  # not use voigt notation -> return 3x3 matrix
except PropertyNotImplementedError:
    pass

In [29]:
##### write trajectory
Trajectory('conf_ase.traj', 'w').write(atoms)

In [ ]:

##### write extxyz
# if Path('file.extXYZ').is_file():
#     os.remove('file.extXYZ')
atoms.write('file_full.extXYZ', format='extxyz', append=True)

cols = ["symbols", "positions", "forces"]
write("file_col.extXYZ", atoms, format="extxyz", columns=cols)

KeyError: 'key from calculator already exists in atoms.info'

In [28]:
atoms.arrays

{'numbers': array([79]), 'positions': array([[0., 5., 5.]])}

In [29]:
atoms.info

{}

In [38]:
atoms.calc.__dict__

{'parallel': {'kpt': None,
  'domain': None,
  'band': None,
  'order': 'kdb',
  'stridebands': False,
  'augment_grids': False,
  'sl_auto': False,
  'sl_default': None,
  'sl_diagonalize': None,
  'sl_inverse_cholesky': None,
  'sl_lcao': None,
  'sl_lrtddft': None,
  'use_elpa': False,
  'elpasolver': '2stage',
  'buffer_size': None},
 'timer': <ase.utils.timing.Timer at 0x7f655e28fc40>,
 'scf': <gpaw.scf.SCFLoop at 0x7f655e0bc460>,
 'wfs': <gpaw.wavefunctions.pw.PWWaveFunctions at 0x7f655e01bdc0>,
 'density': <gpaw.wavefunctions.pw.ReciprocalSpaceDensity at 0x7f655e0102b0>,
 'hamiltonian': <gpaw.wavefunctions.pw.ReciprocalSpaceHamiltonian at 0x7f655e0103d0>,
 'spos_ac': array([[0. , 0.5, 0.5]]),
 'observers': [],
 'initialized': True,
 'world': <MPI at 0x7f658a780150>,
 'log': <gpaw.io.logger.GPAWLogger at 0x7f655e28fbb0>,
 'reader': None,
 'atoms': Atoms(symbols='Au', pbc=True, cell=[2.9, 10.0, 10.0]),
 'results': {'energy': -2.2428277968240597,
  'free_energy': -2.377965829612936

In [14]:
atoms.__dict__

{'_cellobj': Cell([2.9, 10.0, 10.0]),
 '_pbc': array([ True,  True,  True]),
 'arrays': {'numbers': array([79]), 'positions': array([[0., 5., 5.]])},
 '_celldisp': array([[0.],
        [0.],
        [0.]]),
 '_constraints': [],
 'info': {},
 '_calc': <gpaw.calculator.GPAW at 0x7fecb0875bd0>}

In [15]:
atoms.calc.results

{'energy': -2.2428277965913064,
 'free_energy': -2.3779658294208836,
 'dipole': array([ 5.81066569e-15, -2.78452451e-15, -2.56200538e-16]),
 'magmom': 0.0,
 'magmoms': array([0.]),
 'forces': array([[-5.0706073e-30,  0.0000000e+00,  0.0000000e+00]]),
 'stress': array([ 2.02046073e-02,  1.10766539e-03,  1.10766539e-03,  0.00000000e+00,
         0.00000000e+00, -1.76830736e-32])}

In [32]:
help(atoms.get_stress)

Help on method get_stress in module ase.atoms:

get_stress(voigt=True, apply_constraint=True, include_ideal_gas=False) method of ase.atoms.Atoms instance
    Calculate stress tensor.
    
    Returns an array of the six independent components of the
    symmetric stress tensor, in the traditional Voigt order
    (xx, yy, zz, yz, xz, xy) or as a 3x3 matrix.  Default is Voigt
    order.
    
    The ideal gas contribution to the stresses is added if the
    atoms have momenta and ``include_ideal_gas`` is set to True.



In [5]:
atoms.info

{}

In [25]:
cols = ["symbols", "positions"] + [key for key in atoms.arrays if key not in ["symbols", "positions", 'numbers']] + [key for key in atoms.calc.results if key not in ["dipole", "magmom", 'magmoms']]
cols

['symbols',
 'positions',
 'energy',
 'free_energy',
 'dipole',
 'magmom',
 'magmoms',
 'forces',
 'stress']

## Read properties from traj

In [30]:
### Read by dpdata
import dpdata

data = dpdata.LabeledSystem('conf_ase.traj', fmt='ase/traj')
data

Data Summary
Labeled System
-------------------
Frame Numbers      : 1
Atom Numbers       : 1
Including Virials  : Yes
Element List       :
-------------------
Au
1

In [3]:
traj = Trajectory('conf_ase.traj')
a = traj[0]

NameError: name 'Trajectory' is not defined

In [2]:
a.get_forces()

NameError: name 'a' is not defined

In [1]:
# ! pip install git+https://github.com/thangckt/dpdata@devel

# Combine `atoms`

In [ ]:
from ase import Atoms
from ase.build.tools import stack  # noqa
from ase.io import read
from ase.visualize import view

atoms = Atoms("Au", positions=[[0, 2, 2]], cell=[5, 5, 5], pbc=[1, 0, 0])
atoms2 = read("test_file/CH4.data", format="lammps-data")

# system = stack(atoms, atoms2)
view(atoms)

<Popen: returncode: None args: ['/home/tha/app/miniforge/envs/py13/bin/pytho...>

# Atoms' cell

## Make *upper triangular matrix* cell
Atoms with a box is an *upper triangular matrix* is a requirement to use `NPT` ensemble in `ase.md.npt.NPT`. Which implenented
- Nose-Hoover thermostat
- Parrinello-Rahman barostat

The below code to create the `Atoms` object with an upper triangular matrix box, as [this comments](https://gitlab.com/ase/ase/-/merge_requests/3277#note_2255046877)

In [4]:
from ase.build import bulk
from ase.visualize import view

atoms = bulk("Cu", "fcc")
atoms = atoms.repeat((2, 2, 2))
view(atoms)  # viewer="x3d"

<Popen: returncode: None args: ['/home/tha/app/miniforge/envs/py13/bin/pytho...>

In [4]:
from ase.build import make_supercell

print("Initial cell:")
print(atoms.cell.array)

# Make lower-triangular form
atoms.set_cell(atoms.cell.standard_form()[0], strain_atoms=True)

# Permute a and c axes
atoms = make_supercell(atoms, [[0, 0, 1], [0, 1, 0], [1, 0, 0]])

### Now we have something like
# # #
# # 0
# 0 0
### So exchange x and z directions by rotating about y
# # #      # # #
# # 0  ->  0 # #
# 0 0      0 0 #

atoms.rotate(90, "y", rotate_cell=True)

print("Cell after rotation/permutation:")
print(atoms.cell.array)

Initial cell:
[[ 4.16846894e+00  1.47377633e+00 -2.55265548e+00]
 [ 1.56305068e-16  4.42132899e+00 -2.55265548e+00]
 [ 3.12610136e-16  0.00000000e+00 -5.10531096e+00]]
Cell after rotation/permutation:
[[-4.16846894e+00 -1.47377633e+00  2.55265548e+00]
 [-1.56305068e-16 -4.42132899e+00  2.55265548e+00]
 [-3.12610136e-16  0.00000000e+00  5.10531096e+00]]


Details:

In [9]:
### Initial cell:
cell = atoms.cell
cell

Cell([[0.0, 3.61, 3.61], [3.61, 0.0, 3.61], [3.61, 3.61, 0.0]])

In [8]:
cell[1]

array([3.61, 0.  , 3.61])

In [14]:
# Make lower-triangular form
atoms.set_cell(atoms.cell.standard_form()[0], strain_atoms=True)
atoms.cell.array

array([[ 5.10531096,  0.        , -0.        ],
       [ 2.55265548,  4.42132899, -0.        ],
       [ 2.55265548,  1.47377633,  4.16846894]])

In [15]:
from ase.build import make_supercell

# Permute a and c axes
atoms = make_supercell(atoms, [[0, 0, 1], [0, 1, 0], [1, 0, 0]])
atoms.cell.array

array([[2.55265548, 1.47377633, 4.16846894],
       [2.55265548, 4.42132899, 0.        ],
       [5.10531096, 0.        , 0.        ]])

In [16]:
atoms.rotate(90, "y", rotate_cell=True)
atoms.cell.array

array([[ 4.16846894e+00,  1.47377633e+00, -2.55265548e+00],
       [ 1.56305068e-16,  4.42132899e+00, -2.55265548e+00],
       [ 3.12610136e-16,  0.00000000e+00, -5.10531096e+00]])

In [22]:
import numpy as np

new_cell = np.round(atoms.cell.array, 9)
atoms.set_cell(new_cell, strain_atoms=True)
atoms.cell.array

array([[ 4.16846894,  1.47377633, -2.55265548],
       [ 0.        ,  4.42132899, -2.55265548],
       [ 0.        ,  0.        , -5.10531096]])

In [19]:
atoms.cell.array

array([[ 4.16846894e+00,  1.47377633e+00, -2.55265548e+00],
       [ 1.56305068e-16,  4.42132899e+00, -2.55265548e+00],
       [ 3.12610136e-16,  0.00000000e+00, -5.10531096e+00]])

## Scale cell
IMPORTANT: For general (non-orthogonal) cells, the cell vectors are not aligned with Cartesian axes. Instead of modifying only the diagonal components, we should scale the entire cell vectors proportionally along their directions and shift atom positions accordingly.

Example (orthorhombic cell):
```python
# Assumes diagonal cell
new_lengths = [cell[i, i] + distances[i] for i in range(3)]
new_cell = np.diag(new_lengths)
```

Example (triclinic cell):
```python
# Scales full vectors in their own directions
new_lengths = [cell[i] + (distances[i] * cell[i] / np.linalg.norm(cell[i])) for i in range(3)]
new_cell = np.array(new_lengths)
```

In [8]:
from ase.build import bulk

atoms = bulk("Cu", "fcc")
atoms = atoms.repeat((2, 2, 2))
atoms.cell.array

array([[0.  , 3.61, 3.61],
       [3.61, 0.  , 3.61],
       [3.61, 3.61, 0.  ]])

In [9]:
cell = atoms.get_cell()
cell[2, 2] += 2
atoms.set_cell(cell, scale_atoms=False)
atoms.cell.array

array([[0.  , 3.61, 3.61],
       [3.61, 0.  , 3.61],
       [3.61, 3.61, 2.  ]])